export const userFields = {
  name: "",
  email: "",
  phone: "",
  profileImage: "",
  age: null,
  gender: "",
  height: null,
  weight: null,
  goal: "Maintain",
  fitnessLevel: "Beginner",
  bmi: null,
  subscriptionPlan: "Free",
  subscriptionExpiry: null,
  workoutStreak: 0,
  caloriesBurned: 0,
  resetPasswordToken: "",
  resetPasswordExpiry: null,
};

export const profileWritableFields = [
  "name",
  "phone",
  "profileImage",
  "age",
  "gender",
  "height",
  "weight",
  "goal",
  "fitnessLevel",
  "subscriptionPlan",
  "subscriptionExpiry",
  "workoutStreak",
  "caloriesBurned",
];
